const $=id=>document.getElementById(id),N=id=>Number($(id).value)||0,M=n=>"¥"+n.toLocaleString("zh-CN",{maximumFractionDigits:2});
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tool").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tool).classList.add("active")});
function calcTax(){let a=N("taxAmount"),r=N("taxRate")/100;if($("taxType").value==="inclusive"){let ex=a/(1+r);$("taxResult").textContent=`不含税金额：${M(ex)}\n税额：${M(a-ex)}\n含税金额：${M(a)}`}else{$("taxResult").textContent=`不含税金额：${M(a)}\n税额：${M(a*r)}\n含税金额：${M(a*(1+r))}`}}
function calcProfit(){let i=N("income"),c=N("cost")+N("otherCost"),p=i-c;$("profitResult").textContent=`预计总成本：${M(c)}\n预计利润：${M(p)}\n收入利润率：${i?(p/i*100).toFixed(2):0}%\n成本利润率：${c?(p/c*100).toFixed(2):0}%`}
function calcBid(){let c=N("controlPrice"),r=N("targetRate")/100,b=N("myBid"),line=c*r;$("bidResult").textContent=`${(r*100).toFixed(2)}%比例线：${M(line)}\n拟报价占控制价：${c?(b/c*100).toFixed(4):0}%\n拟报价与比例线差额：${M(b-line)}`}
function calcPayment(){let v=N("completed"),pr=N("payRate")/100,rr=N("retentionRate")/100,paid=N("paid"),ret=v*rr,due=v*pr-ret-paid;$("paymentResult").textContent=`按支付比例计算：${M(v*pr)}\n本期质保金：${M(ret)}\n扣除已支付后本期参考应付：${M(due)}`}
function calcGuarantee(){let b=N("guaranteeBase"),r=N("guaranteeRate")/100,cap=N("guaranteeCap"),raw=b*r,final=cap?Math.min(raw,cap):raw;$("guaranteeResult").textContent=`按比例测算：${M(raw)}${cap?`\n按填写上限取值：${M(final)}`:""}\n请以招标文件明确金额和形式为准。`}
function upperMoney(n){if(!isFinite(n)||n<0||n>9999999999999.99)return"金额超出支持范围";const C="零壹贰叁肆伍陆柒捌玖",U=["","拾","佰","仟"],B=["","万","亿","兆"];n=Math.round(n*100);let integer=Math.floor(n/100),jiao=Math.floor(n/10)%10,fen=n%10;if(integer===0)return"人民币零元"+(jiao?C[jiao]+"角":"")+(fen?C[fen]+"分":"整");let parts=[],bi=0;while(integer>0){let group=integer%10000,s="",zero=false;for(let i=0;i<4;i++){let d=Math.floor(group/Math.pow(10,i))%10;if(d){s=C[d]+U[i]+(zero?"零":"")+s;zero=false}else if(s)zero=true}if(group)parts.unshift(s+B[bi]);else if(parts.length&&!parts[0].startsWith("零"))parts.unshift("零");integer=Math.floor(integer/10000);bi++}let body=parts.join("").replace(/零+/g,"零").replace(/零$/,"");return"人民币"+body+"元"+(jiao?C[jiao]+"角":"")+(fen?C[fen]+"分":jiao?"":"整")}
function calcUpper(){$("upperResult").textContent=upperMoney(N("upperAmount"))}
function calcDate(){let d=new Date($("startDate").value+"T00:00:00"),days=Math.max(0,Math.floor(N("duration")));if(isNaN(d))return $("dateResult").textContent="请选择开始日期";let add=$("dateMode").value==="inclusive"?Math.max(0,days-1):days;d.setDate(d.getDate()+add);$("dateResult").textContent=`预计完成日期：${d.toLocaleDateString("zh-CN")}\n日历工期：${days}天`}
function calcAverage(){let a=$("values").value.split(/[\s,，;；]+/).map(Number).filter(Number.isFinite);if(!a.length)return $("averageResult").textContent="请输入有效报价";let sum=a.reduce((x,y)=>x+y,0),avg=sum/a.length,sorted=[...a].sort((x,y)=>x-y),mid=sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2;$("averageResult").textContent=`有效报价数量：${a.length}\n平均值：${M(avg)}\n中位数：${M(mid)}\n最低：${M(sorted[0])}\n最高：${M(sorted.at(-1))}`}
$("startDate").value=new Date().toISOString().slice(0,10);calcTax();